export enum AccessorTypeEnum {
  BALANCE = 'balance',
  DATA = 'data',
  SIGNERS = 'signers',
  FLAGS = 'flags',
}

export const OPERATION_THRESHOLD = {
  createAccount: 'med_threshold',
  payment: 'med_threshold',
  pathPaymentStrictReceive: 'med_threshold',
  pathPaymentStrictSend: 'med_threshold',
  createPassiveSellOffer: 'med_threshold',
  manageSellOffer: 'med_threshold',
  manageBuyOffer: 'med_threshold',
  setOptions: 'high_threshold',
  changeTrust: 'med_threshold',
  allowTrust: 'low_threshold',
  accountMerge: 'high_threshold',
  inflation: 'med_threshold',
  manageData: 'medium_threshold',
  bumpSequence: 'low_threshold',
  createClaimableBalance: 'med_threshold',
  claimClaimableBalance: 'low_threshold',
  beginSponsoringFutureReserves: 'med_threshold',
  endSponsoringFutureReserves: 'med_threshold',
  revokeSponsorship: 'med_threshold',
  clawback: 'med_threshold',
  clawbackClaimableBalance: 'med_threshold',
  setTrustLineFlags: 'low_threshold',
  liquidityPoolDeposit: 'med_threshold',
  liquidityPoolWithdraw: 'med_threshold',
  invokeHostFunction: 'med_threshold',
  extendFootprintTtl: 'med_threshold',
  restoreFootprint: 'med_threshold',
};
